[wysiwyg] Fix handling of url params on internal links
novius-os/core pull request #276
Opened 2017-03-23 09:42 UTC by Meroje

- Question mark is automatically added if omitted by the user
- Old params are properly removed from the hidden input to avoid duplicating

2017-03-23 10:13 UTC, DOMEYD commented
:+1:

2017-03-30 09:39 UTC, shaoshiva requested changes

2017-03-30 09:39 UTC, shaoshiva commented on static/admin/novius-os/js/page/jquery.novius-os.link-wysiwyg.js
> +                                    var url_params = $input_url_params.val().charAt(0) === '?' ? $input_url_params.val() : '?' + $input_url_params.val();
```
var url_params = $input_url_params.val();
if (url_params.charAt(0) !== '?') {
    url_params = '?' + url_params;
}
```

2017-04-10 16:31 UTC, Meroje commented on static/admin/novius-os/js/page/jquery.novius-os.link-wysiwyg.js
> +                                    var url_params = $input_url_params.val().charAt(0) === '?' ? $input_url_params.val() : '?' + $input_url_params.val();
done

2017-04-10 16:39 UTC, jguyomard approved these changes

2017-04-11 09:04 UTC, shaoshiva approved these changes

2017-04-11 09:49 UTC, merged