Allows to duplicate a menu from application menu
novius-os/core pull request #300
Opened 2017-11-08 11:15 UTC by wprod

The idea is to propose to users the ability to duplicate a menu. 
On duplication a popin shows giving the user the ability to select one or many context.

:warning: The duplicated menues wont be considered as translations and will all be independants.

2017-11-08 11:24 UTC, SwithFr commented on framework/applications/noviusos_menu/lang/fr/common.lang.php
> +    'Here you are ! The menu has just been duplicated.' => 'Le menu a bien été dupliqué.',
no space before "!" :)

2017-11-08 11:28 UTC, shaoshiva requested changes

2017-11-08 11:28 UTC, shaoshiva commented on framework/applications/noviusos_menu/classes/controller/admin/menu/crud.ctrl.php
> +                $context = !empty($duplicateContext) ? $duplicateContext : $menu->menu_context;
Better use `$menu->getContext()` instead of `$menu->menu_context`.

2017-11-09 17:00 UTC, mesa-novius commented on framework/applications/noviusos_menu/classes/model/menu.model.php
> +use Fuel\Core\Log;
It seems you do not use Log

2017-11-09 17:10 UTC, mesa-novius commented on framework/applications/noviusos_menu/classes/controller/admin/menu/crud.ctrl.php
> +    public function action_duplicate($id = null)
are we supposed to duplicate existing items? do you accept null as id?

2017-11-09 17:32 UTC, mesa-novius commented on framework/applications/noviusos_menu/classes/model/menu.model.php
> +            $clone = clone $item;
Why does the menu know how to duplicate menu_items? I think the duplication of a menu_item should be a task of a menu_item.

2017-11-09 17:34 UTC, mesa-novius commented on framework/applications/noviusos_menu/classes/model/menu.model.php
> +                    static::duplicateMenuItems($this, $clone);
Why do you need statically call duplicateMenuItems and duplicateMenuItems in this context?

2017-11-21 13:28 UTC, shaoshiva approved these changes

2017-11-29 17:15 UTC, Seb-C requested changes

2017-11-29 17:15 UTC, Seb-C commented on framework/applications/noviusos_menu/classes/model/menu/item.model.php
> +        };
There shouldn't be a semicolon here

2017-11-29 17:15 UTC, Seb-C commented on framework/applications/noviusos_menu/lang/fr/common.lang.php
> +    '(copy)' => '(copie)',
I think the key should be `' (copy)'` and not  `'(copy)'`.

2017-11-30 10:44 UTC, jguyomard commented
@Seb-C @shaoshiva I just add some fixes (see https://github.com/novius-os/core/pull/300/commits/16a12601430880eee68b8f88c9ec979903f9b7f7)

2017-11-30 11:16 UTC, Seb-C approved these changes

2017-12-04 07:55 UTC, merged